name: Deploy to Koyeb

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/advshop-app:latest .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/advshop-app:latest

      - name: Redeploy on Koyeb
        run: |
          curl -X POST "https://app.koyeb.com/v1/apps/YOUR_KOYEB_APP_ID/deploy" \
          -H "Authorization: Bearer ${{ secrets.KOYEB_API_TOKEN }}"

      - name: Done!
        run: echo "Deployment to Koyeb completed successfully.